### ISSUE TITLE
Strange logging issue

### ISSUE THREAD

**Issue by rchillyard** [rchillyard/Number#72]
Sometimes we get an exception like this (which doesn't immediately lend itself to recognition):
11:16:08,721 |-ERROR in ch.qos.logback.classic.pattern.LoggerConverter@1c93f6e1 - failed to parse integer string [1.] java.lang.NumberFormatException: For input string: "1."
	at java.lang.NumberFormatException: For input string: "1."
	at 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at 	at java.base/java.lang.Integer.parseInt(Integer.java:668)
	at 	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at 	at ch.qos.logback.classic.pattern.NamedConverter.start(NamedConverter.java:92)
	at 	at ch.qos.logback.core.pattern.ConverterUtil.startConverters(ConverterUtil.java:37)
	at 	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:90)
	at 	at ch.qos.logback.classic.encoder.PatternLayoutEncoder.start(PatternLayoutEncoder.java:28)
	at 	at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandleComplex(ImplicitModelHandler.java:208)
	at 	at ch.qos.logback.core.model.processor.ImplicitModelHandler.postHandle(ImplicitModelHandler.java:186)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:257)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
	at 	at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:210)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:174)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:126)
	at 	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:69)
	at 	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:34)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:98)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:50)
	at 	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:167)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:154)
	at 	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:437)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:372)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:398)
	at 	at com.phasmidsoftware.matchers.MatchLogger$.apply(Adjunct.scala:138)
	at 	at com.phasmidsoftware.matchers.MatchLogger$.<clinit>(Adjunct.scala:134)
	at 	at com.phasmidsoftware.number.core.Expression$.<clinit>(Expression.scala:72)
	at 	at com.phasmidsoftware.number.core.BaseComplex.power(BaseComplex.scala:75)
	at 	at com.phasmidsoftware.number.core.BaseComplex.power(BaseComplex.scala:96)
	at 	at com.phasmidsoftware.number.core.ComplexSpec.$anonfun$new$17(ComplexSpec.scala:120)
	at 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at 	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at 	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at 	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at 	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1832)
	at 	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at 	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at 	at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1686)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1830)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1842)
	at 	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1842)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1824)
	at 	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1686)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1900)
	at 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at 	at scala.collection.immutable.List.foreach(List.scala:333)
	at 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at 	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at 	at scala.collection.immutable.List.foreach(List.scala:333)
	at 	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at 	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at 	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1900)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1899)
	at 	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1686)
	at 	at org.scalatest.Suite.run(Suite.scala:1114)
	at 	at org.scalatest.Suite.run$(Suite.scala:1096)
	at 	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1686)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1945)
	at 	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1945)
	at 	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1943)
	at 	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1686)
	at 	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:47)
	at 	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1321)
	at 	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1315)
	at 	at scala.collection.immutable.List.foreach(List.scala:333)
	at 	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1315)
	at 	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
	at 	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
	at 	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
	at 	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
	at 	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at 	at org.scalatest.tools.Runner.run(Runner.scala)
	at 	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:43)
	at 	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:26)

**Comment by rchillyard** [comment]
This has to do with the log4j/logback configuration. I believe it is fixed now.
